### ISSUE TITLE
 Remotes registry file missing

### ISSUE THREAD

**Issue by SonwYang** [soduco/ICDAR-2021-Vectorization#1] opened 2022-03-30 03:43 UTC
Hello, bro! When I rebuild the watershed project, I encountered a warning: Remotes registry file missing, creating default one in /home/zc/.conan/remotes.jso. And I can't run this project. How can I solve it? Looking forward to your reply!!!

**Comment by jchazalon** [comment] 2022-03-30 08:11
Hi @SonwYang,

Thank your for taking the time to report an issue.

The warning is a normal message from the Conan system (creating a default configuration file when none is found), and is not the cause of your trouble.

Can you please provide more information about your problem so we can help you?

- Operating system used and version
- Log of the build (as attachment)
- Python version
- Conan version
- cmake version

Eventually, we can share a Dockerfile to make the build more easily reproducible; would this help you?

Best,

**Comment by jchazalon** [comment] 2022-03-30 08:12
@Edwin-Carlinet I see we depend on the unstable build of Pylene [here](https://github.com/soduco/ICDAR-2021-Vectorization/blob/main/watershed/histmapseg/conanfile.txt), can this be linked?

**Comment by SonwYang** [comment] 2022-03-30 08:15
```
(base) zc@zc:~/yp/cropland/ICDAR-2021-Vectorization-main/watershed/histmapseg$ conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake
ERROR: Conanfile not found at /home/zc/yp/cropland/ICDAR-2021-Vectorization-main/watershed/conanfile.py or /home/zc/yp/cropland/ICDAR-2021-Vectorization-main/watershed/conanfile.txt
(base) zc@zc:~/yp/cropland/ICDAR-2021-Vectorization-main/watershed/histmapseg$ mkdir newbuild && cd newbuild
(base) zc@zc:~/yp/cropland/ICDAR-2021-Vectorization-main/watershed/histmapseg/newbuild$ conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

pylene/head@lrde/unstable: Not found in local cache, looking in remotes...
pylene/head@lrde/unstable: Trying with 'conancenter'...
pylene/head@lrde/unstable: Trying with 'lrde-public'...

ERROR: HTTPSConnectionPool(host='artifactory.lrde.epita.fr', port=443): Max retries exceeded with url: /artifactory/api/conan/lrde-public/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fab83e16670>, 'Connection to artifactory.lrde.epita.fr timed out. (connect timeout=60.0)'))

Unable to connect to lrde-public=https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

**Comment by jchazalon** [comment] 2022-03-30 09:51
@SonwYang This seems to be on our side, our repo went down for a short time. Sorry about that.

This seem to work now, as I was able to reproduce the build and launch the program on an Ubuntu 20.04.4 LTS system. 

**Can you confirm you can build now?**

If you are using a recent version of Ubuntu, you may need to activate the PIE compilation: change the line
```shell
conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake
```
with (add `--build pylene` to avoid reusing the non-PIE code from our repo):
```shell
conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake --build pylene
```
We will update the documentation accordingly.

Thanks @Edwin-Carlinet  for helping me.

**Comment by SonwYang** [comment] 2022-03-31 01:35
Hi, I feel so sorry to tell you that l failed again. This is the detailed information: 
```
(py37) scell@scell-mcu:~/medicalSeg/ICDAR-2021-Vectorization-main$ conan remote add lrde-public https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public
WARN: Remotes registry file missing, creating default one in /home/scell/.conan/remotes.json
(py37) scell@scell-mcu:~/medicalSeg/ICDAR-2021-Vectorization-main$ cd ./watershed/histmapseg/
(py37) scell@scell-mcu:~/medicalSeg/ICDAR-2021-Vectorization-main/watershed/histmapseg$ mkdir newbuild && cd newbuild
(py37) scell@scell-mcu:~/medicalSeg/ICDAR-2021-Vectorization-main/watershed/histmapseg/newbuild$ conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake --build pylene
Auto detecting your dev setup to initialize the default profile (/home/scell/.conan/profiles/default)
Found gcc 9
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/scell/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=9
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /home/scell/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

pylene/head@lrde/unstable: Not found in local cache, looking in remotes...
pylene/head@lrde/unstable: Trying with 'conancenter'...
pylene/head@lrde/unstable: Trying with 'lrde-public'...
ERROR: HTTPSConnectionPool(host='artifactory.lrde.epita.fr', port=443): Max retries exceeded with url: /artifactory/api/conan/lrde-public/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2022c4a090>, 'Connection to artifactory.lrde.epita.fr timed out. (connect timeout=60.0)'))

Unable to connect to lrde-public=https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

```

**Comment by jchazalon** [comment] 2022-03-31 15:20
Dear @SonwYang ,
thanks again for taking the time to make some tests.

The relevant error message is
```
ERROR: HTTPSConnectionPool(host='artifactory.lrde.epita.fr', port=443): Max retries exceeded with url: /artifactory/api/conan/lrde-public/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2022c4a090>, 'Connection to artifactory.lrde.epita.fr timed out. (connect timeout=60.0)'))
```
This indicates our network is having some issues accepting your connection.

We contacted our administrator and the problem should be fixed.

Can you retry the following command?
```
conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake --build pylene
```

If it is still failing, can you please share with us the output of the following command? (It tests the connectivity to our repo.)
```bash
curl -vH --url https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public/v1/ping
```

**Comment by SonwYang** [comment] 2022-04-07 06:29
I tried it again, but it failed. The details is as follows:
`[ 41%] Building CXX object pylene/CMakeFiles/Pylene-core.dir/src/morpho/block_running_max.cpp.o
In file included from /home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/pylene/include/mln/accu/composite_accumulator.hpp:3,
                 from /home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/pylene/include/mln/accu/accumulator.hpp:3,
                 from /home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/pylene/include/mln/morpho/component_tree.hpp:4,
                 from /home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/pylene/src/morpho/component_tree.cpp:1:
/home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/pylene/include/mln/accu/concept/accumulator.hpp:4:10: fatal error: concepts: No such file or directory
    4 | #include <concepts>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [pylene/CMakeFiles/Pylene-core.dir/build.make:271: pylene/CMakeFiles/Pylene-core.dir/src/morpho/component_tree.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:241: pylene/CMakeFiles/Pylene-core.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
pylene/head@lrde/unstable: 
pylene/head@lrde/unstable: ERROR: Package 'c0cf748d507ec220d2456b2432732d142e31f560' build failed
pylene/head@lrde/unstable: WARN: Build folder /home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/build
ERROR: pylene/head@lrde/unstable: Error in build() method, line 108
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/home/zc/.conan/data/pylene/head/lrde/unstable/build/c0cf748d507ec220d2456b2432732d142e31f560/build' '--' '-j8'
`
when I run this command:
`curl -vH --url https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public/v1/ping`

It seems ok.

`(yp) zc@zc:~/yp/cropland/ICDAR-2021-Vectorization-main/watershed/histmapseg/newbuild$ curl -vH --url https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public/v1/ping
*   Trying 91.243.117.236:443...
* Connected to artifactory.lrde.epita.fr (91.243.117.236) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/zc/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=artifactory.lrde.epita.fr
*  start date: Mar 30 12:27:10 2022 GMT
*  expire date: Jun 28 12:27:09 2022 GMT
*  subjectAltName: host "artifactory.lrde.epita.fr" matched cert's "artifactory.lrde.epita.fr"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /artifactory/api/conan/lrde-public/v1/ping HTTP/1.1
> Host: artifactory.lrde.epita.fr
> User-Agent: curl/7.71.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< Date: Thu, 07 Apr 2022 06:25:32 GMT
< Server: Caddy
< X-Artifactory-Id: b91f9e23c04fffcf:-6da9d9ca:17f6f36d9d1:-8000
< X-Artifactory-Node-Id: dff78e73a362
< X-Conan-Server-Capabilities: complex_search,checksum_deploy,revisions,matrix_params
< X-Conan-Server-Version: 0.20.0
< X-Jfrog-Version: Artifactory/7.29.8 72908900
< 
* Connection #0 to host artifactory.lrde.epita.fr left intact
`

**Comment by Edwin-Carlinet** [comment] 2022-04-07 07:37
Your compiler is outdated. You need at least gcc-10 (or clang-10)

These compilers are available on Ubuntu 20 LTS (apt install gcc-10) and Debian (the default compiler).

If you install a new compiler, do not forget to upgrade your conan default profile (``~/.conan/profile/default``)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=gcc-10
CXX=g++-10
```

**Comment by jchazalon** [comment] 2022-05-18 09:05
Closing because of inactivity.
Feel free to reopen if needed.

**Closed as completed by jchazalon** 2022-05-18 09:05 UTC

**Comment by SonwYang** [comment] 2022-10-11 06:59
(base) ***@***.***:~/yp/cropland/ICDAR-2021-Vectorization-main/watershed/histmapseg/newbuild$ conan install .. --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g cmake
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]


***@***.***/unstable: Not found in local cache, looking in remotes...
***@***.***/unstable: Trying with 'conancenter'...
***@***.***/unstable: Trying with 'lrde-public'...


ERROR: HTTPSConnectionPool(host='artifactory.lrde.epita.fr', port=443): Max retries exceeded with url: /artifactory/api/conan/lrde-public/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fab83e16670&gt;, 'Connection to artifactory.lrde.epita.fr timed out. (connect timeout=60.0)'))


Unable to connect to lrde-public=https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 下午4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [soduco/ICDAR-2021-Vectorization]  Remotes registry file missing (Issue #1)





 
Hi @SonwYang,
 
Thank your for taking the time to report an issue.
 
The warning is a normal message from the Conan system (creating a default configuration file when none is found), and is not the cause of your trouble.
 
Can you please provide more information about your problem so we can help you?
  
Operating system used and version
 
Log of the build (as attachment)
 
Python version
 
Conan version
 
cmake version
  
Eventually, we can share a Dockerfile to make the build more easily reproducible; would this help you?
 
Bestn

**Comment by jchazalon** [comment] 2022-10-20 20:38
Hi @SonwYang , sorry to get back to you late.
We had a massive change of domain names due to some renaming of our lab.
This broke some services for a while, but everything should be up again now.
@Edwin-Carlinet  could you please make sure that the artifactory server is properly running now?

However, you may now update all your URLs to change "lrde.epita.fr" to "lre.epita.fr" (yes, this is terribly annoying).
Sorry for the inconvenience.

**Comment by Eunoia** [comment] 2025-08-28 16:46
Howdy!

I am trying to segment [index pages for sanborn maps](https://www.loc.gov/resource/g4364om.g4364om_g00727195003/?sp=6&r=0.074,0.628,1.059,0.565,0) using the [Benchmark modern historical map vectorization processes
](https://github.com/soduco/Benchmark_historical_map_vectorization) repo.

It needs to run `histmapseg`, which requires compiling it for my older intel mac from 2020. Building with conan has a dependency on pylene. I'm not able to install pylene via conan because my computer says artifactory.lre.epita.fr is down. When I compile pylene from scratch, it requires a custom version of freeimage from lre which I don't know how to find. 

I ran the curl command commands above to see if I have access to the domain, and it looks like the url points to an internal private IP address? For reference, my computer's IP address is 192.168.0.111 and there are no hosts within 192.168.100 /24 

```sh
curl -vH --url https://artifactory.lre.epita.fr/artifactory/api/conan/lre-public/v1/ping                                             [ruby-2.5.5]
* Host artifactory.lre.epita.fr:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.100.28
*   Trying 192.168.100.28:443...
* connect to 192.168.100.28 port 443 from 192.168.0.111 port 54853 failed: Operation timed out
* Failed to connect to artifactory.lre.epita.fr port 443 after 75003 ms: Could not connect to server
* closing connection #0
curl: (28) Failed to connect to artifactory.lre.epita.fr port 443 after 75003 ms: Could not connect to server
```

Doing an ns lookup on the domain and artifactory is now for docker?

```sh
$ nslookup artifactory.lre.epita.fr 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
artifactory.lre.epita.fr	canonical name = docker.lre.epita.fr.
Name:	docker.lre.epita.fr
Address: 192.168.100.28
```

Maybe this is a platform issue with my system, or a DNS issue. Given the time drift, it could also be the URL changed, but it wasn't updated on these repos for departmental reasons. I could also just be using the wrong code for my problem. Maybe the histmapseg program is deprecated, I'm not sure.

**Comment by Edwin-Carlinet** [comment] 2025-08-28 20:22
Thank you for reporting this issue. The artifactory is indeed down. We have reported this issue to our IT System Department.  We let you know when it is fixed.

**Comment by Edwin-Carlinet** [comment] 2025-08-29 14:55
Hello @Eunoia , artifactory.lre.epita.fr is now up. Can you try again ?

**Comment by Eunoia** [comment] 2025-08-31 16:55
@Edwin-Carlinet The server is up, and I am able to get the program to run on my machine! The final confusion to overcome is that the domain is the new lab's name, and the path is the old name of the lab. 

```diff
- https://artifactory.lrde.epita.fr/artifactory/api/conan/lrde-public
+ https://artifactory.lre.epita.fr/artifactory/api/conan/lrde-public
```
